# Generated by Django 5.1.6 on 2025-03-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='image',
        ),
    ]
