# Generated by Django 5.1.6 on 2025-03-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_resource_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('savings', 'Ahorro')], max_length=10),
        ),
    ]
