# Generated by Django 5.1.6 on 2025-03-05 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_basicexpense_incomesource_savingsinvestment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
