# Generated by Django 5.1.6 on 2025-03-20 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_populate_modulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminoBasico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminos', to='finance.modulo')),
            ],
        ),
    ]
