# Generated by Django 5.1.6 on 2025-03-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_amount_budget_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
