# Generated by Django 5.1.6 on 2025-03-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_insert_terminos_basicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='ejercicio',
        ),
        migrations.AddField(
            model_name='modulo',
            name='ejercicio_instrucciones',
            field=models.TextField(blank=True, help_text='Ingrese cada instrucción en una nueva línea.', null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='ejercicio_objetivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
