# Generated by Django 5.1.6 on 2025-03-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_transaction_description_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
